ðŸ§  Running BERT on 
ðŸš€ Starting BERT CV for ...
Traceback (most recent call last):
  File "/work/projects/hpcadmins/sw-slcolson/NLP_Disaster_Tweets/run_bert_cv.py", line 109, in <module>
    run_bert_pipeline(dataset_name)
  File "/work/projects/hpcadmins/sw-slcolson/NLP_Disaster_Tweets/run_bert_cv.py", line 16, in run_bert_pipeline
    df = pd.read_csv(f"final_processed/{dataset_name}.csv")
  File "/opt/ohpc/pub/spack/v0.21.1/opt/spack/linux-rocky8-x86_64_v3/gcc-8.5.0/py-pandas-2.1.2-223biyuu3qprro5zar6hfpslt74e63un/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/ohpc/pub/spack/v0.21.1/opt/spack/linux-rocky8-x86_64_v3/gcc-8.5.0/py-pandas-2.1.2-223biyuu3qprro5zar6hfpslt74e63un/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/ohpc/pub/spack/v0.21.1/opt/spack/linux-rocky8-x86_64_v3/gcc-8.5.0/py-pandas-2.1.2-223biyuu3qprro5zar6hfpslt74e63un/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/ohpc/pub/spack/v0.21.1/opt/spack/linux-rocky8-x86_64_v3/gcc-8.5.0/py-pandas-2.1.2-223biyuu3qprro5zar6hfpslt74e63un/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/opt/ohpc/pub/spack/v0.21.1/opt/spack/linux-rocky8-x86_64_v3/gcc-8.5.0/py-pandas-2.1.2-223biyuu3qprro5zar6hfpslt74e63un/lib/python3.10/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'final_processed/.csv'
âœ… Completed  in 30 seconds
